/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "surface-dim": "#d8dadc",
        "secondary": "#505f76",
        "on-surface": "#191c1e",
        "on-tertiary-container": "#27c38a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005236",
        "secondary-container": "#d0e1fb",
        "primary": "#00236f",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#264191",
        "inverse-primary": "#b6c4ff",
        "primary-fixed-dim": "#b6c4ff",
        "surface-container": "#eceef0",
        "tertiary-fixed": "#6ffbbe",
        "secondary-fixed": "#d3e4fe",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#0b1c30",
        "surface": "#f7f9fb",
        "surface-tint": "#4059aa",
        "on-primary-fixed": "#00164e",
        "primary-container": "#1e3a8a",
        "error": "#ba1a1a",
        "surface-container-high": "#e6e8ea",
        "on-background": "#191c1e",
        "surface-container-low": "#f2f4f6",
        "outline-variant": "#c5c5d3",
        "on-error-container": "#93000a",
        "primary-fixed": "#dce1ff",
        "tertiary": "#00311f",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "on-secondary": "#ffffff",
        "on-primary-container": "#90a8ff",
        "tertiary-container": "#004a31",
        "background": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "outline": "#757682"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
}